name: "Danger JS"
on:
  pull_request:
    types: [
      assigned,
      unassigned,
      labeled,
      unlabeled,
      opened,
      edited,
      reopened,
      synchronize,
      ready_for_review,
      review_requested,
      review_request_removed,
    ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: dangerjs
        run: npx danger@10.2.0 ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: "true"
